version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: pub
    directory: /examples/pub
    schedule:
      interval: daily
    groups:
      isar-community:
        patterns:
          - "*"
    allow:
      - dependency-name: isar_community*
