// ignore_for_file: camel_case_types, non_constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<ffi.Uint32> Function(
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external ffi.Pointer<ffi.Uint32> isar_find_word_boundaries(
  ffi.Pointer<ffi.Uint8> input_bytes,
  int length,
  ffi.Pointer<ffi.Uint32> number_words,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint32>, ffi.Uint32)>()
external void isar_free_word_boundaries(
  ffi.Pointer<ffi.Uint32> boundaries,
  int word_count,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void isar_free_string(ffi.Pointer<ffi.Char> string);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int64)>()
external ffi.Pointer<ffi.Char> isar_get_error(int err_code);

@ffi.Native<ffi.Void Function(ffi.Pointer<CObjectSet>)>()
external void isar_free_c_object_set(ffi.Pointer<CObjectSet> ros);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObject>,
  )
>()
external int isar_get(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObject> object,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<CIndexKey>,
    ffi.Pointer<CObject>,
  )
>()
external int isar_get_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<CObject> object,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObjectSet>,
  )
>()
external int isar_get_all(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObjectSet> objects,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<CIndexKey>>,
    ffi.Pointer<CObjectSet>,
  )
>()
external int isar_get_all_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<ffi.Pointer<CIndexKey>> keys,
  ffi.Pointer<CObjectSet> objects,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObject>,
  )
>()
external int isar_put(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObject> object,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<CObject>,
  )
>()
external int isar_put_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<CObject> object,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObjectSet>,
  )
>()
external int isar_put_all(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObjectSet> objects,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<CObjectSet>,
  )
>()
external int isar_put_all_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<CObjectSet> objects,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Int64,
    ffi.Pointer<ffi.Bool>,
  )
>()
external int isar_delete(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int id,
  ffi.Pointer<ffi.Bool> deleted,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<CIndexKey>,
    ffi.Pointer<ffi.Bool>,
  )
>()
external int isar_delete_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Bool> deleted,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<ffi.Int64>,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int isar_delete_all(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<ffi.Int64> ids,
  int ids_length,
  ffi.Pointer<ffi.Uint32> count,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<CIndexKey>>,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int isar_delete_all_by_index(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int index_id,
  ffi.Pointer<ffi.Pointer<CIndexKey>> keys,
  int keys_length,
  ffi.Pointer<ffi.Uint32> count,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<CIsarCollection>, ffi.Pointer<CIsarTxn>)
>()
external int isar_clear(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint32,
  )
>()
external int isar_json_import(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<ffi.Char> id_name,
  ffi.Pointer<ffi.Uint8> json_bytes,
  int json_length,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<ffi.Int64>,
  )
>()
external int isar_count(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<ffi.Int64> count,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Bool,
    ffi.Bool,
    ffi.Pointer<ffi.Int64>,
  )
>()
external int isar_get_size(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  bool include_indexes,
  bool include_links,
  ffi.Pointer<ffi.Int64> size,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObjectSet>,
  )
>()
external int isar_verify(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObjectSet> objects,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Int8 Function(ffi.Int64 port_id, ffi.Pointer<CDartCObject> message)
      >
    >,
  )
>()
external void isar_connect_dart_api(
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int8 Function(ffi.Int64 port_id, ffi.Pointer<CDartCObject> message)
    >
  >
  ptr,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<CFilter>>, ffi.Bool)>()
external void isar_filter_static(
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  bool value,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Bool,
    ffi.Bool,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Uint32,
  )
>()
external void isar_filter_and_or_xor(
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  bool and,
  bool exclusive,
  ffi.Pointer<ffi.Pointer<CFilter>> conditions,
  int length,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<ffi.Pointer<CFilter>>, ffi.Pointer<CFilter>)
>()
external void isar_filter_not(
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<CFilter> condition,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<CFilter>,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_object(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<CFilter> condition,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<CFilter>,
    ffi.Uint64,
  )
>()
external int isar_filter_link(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<CFilter> condition,
  int link_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
  )
>()
external int isar_filter_link_length(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  int lower,
  int upper,
  int link_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_list_length(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  int lower,
  int upper,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_null(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Int64,
    ffi.Bool,
    ffi.Int64,
    ffi.Bool,
  )
>()
external void isar_filter_id(
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  int lower,
  bool include_lower,
  int upper,
  bool include_upper,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Int64,
    ffi.Bool,
    ffi.Int64,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_long(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  int lower,
  bool include_lower,
  int upper,
  bool include_upper,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Double,
    ffi.Double,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_double(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  double lower,
  double upper,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_string(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<ffi.Char> lower,
  bool include_lower,
  ffi.Pointer<ffi.Char> upper,
  bool include_upper,
  bool case_sensitive,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_string_starts_with(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_string_ends_with(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_string_contains(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<ffi.Pointer<CFilter>>,
    ffi.Pointer<ffi.Char>,
    ffi.Bool,
    ffi.Uint64,
    ffi.Uint64,
  )
>()
external int isar_filter_string_matches(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<ffi.Pointer<CFilter>> filter,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
  int embedded_col_id,
  int property_id,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<CIndexKey>>)>()
external void isar_key_create(ffi.Pointer<ffi.Pointer<CIndexKey>> key);

@ffi.Native<ffi.Bool Function(ffi.Pointer<CIndexKey>)>()
external bool isar_key_increase(ffi.Pointer<CIndexKey> key);

@ffi.Native<ffi.Bool Function(ffi.Pointer<CIndexKey>)>()
external bool isar_key_decrease(ffi.Pointer<CIndexKey> key);

@ffi.Native<ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Uint8)>()
external void isar_key_add_byte(ffi.Pointer<CIndexKey> key, int value);

@ffi.Native<ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Int32)>()
external void isar_key_add_int(ffi.Pointer<CIndexKey> key, int value);

@ffi.Native<ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Int64)>()
external void isar_key_add_long(ffi.Pointer<CIndexKey> key, int value);

@ffi.Native<ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Double)>()
external void isar_key_add_float(ffi.Pointer<CIndexKey> key, double value);

@ffi.Native<ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Double)>()
external void isar_key_add_double(ffi.Pointer<CIndexKey> key, double value);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Pointer<ffi.Char>, ffi.Bool)
>()
external void isar_key_add_string(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Pointer<ffi.Char>, ffi.Bool)
>()
external void isar_key_add_string_hash(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Char> value,
  bool case_sensitive,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<CIndexKey>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external void isar_key_add_string_list_hash(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Pointer<ffi.Char>> value,
  int length,
  bool case_sensitive,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
>()
external void isar_key_add_byte_list_hash(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Uint8> value,
  int length,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Pointer<ffi.Int32>, ffi.Uint32)
>()
external void isar_key_add_int_list_hash(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Int32> value,
  int length,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CIndexKey>, ffi.Pointer<ffi.Int64>, ffi.Uint32)
>()
external void isar_key_add_long_list_hash(
  ffi.Pointer<CIndexKey> key,
  ffi.Pointer<ffi.Int64> value,
  int length,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> isar_version();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> isar_mdbx_version();

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<ffi.Pointer<CIsarInstance>>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Double,
  )
>()
external int isar_instance_create(
  ffi.Pointer<ffi.Pointer<CIsarInstance>> isar,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Char> schema_json,
  int max_size_mib,
  bool relaxed_durability,
  int compact_min_file_size,
  int compact_min_bytes,
  double compact_min_ratio,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Pointer<CIsarInstance>>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
    ffi.Bool,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Double,
    ffi.Int64,
  )
>()
external void isar_instance_create_async(
  ffi.Pointer<ffi.Pointer<CIsarInstance>> isar,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<ffi.Char> path,
  ffi.Pointer<ffi.Char> schema_json,
  int max_size_mib,
  bool relaxed_durability,
  int compact_min_file_size,
  int compact_min_bytes,
  double compact_min_ratio,
  int port,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<CIsarInstance>)>()
external bool isar_instance_close(ffi.Pointer<CIsarInstance> isar);

@ffi.Native<ffi.Bool Function(ffi.Pointer<CIsarInstance>)>()
external bool isar_instance_close_and_delete(ffi.Pointer<CIsarInstance> isar);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<CIsarInstance>)>()
external ffi.Pointer<ffi.Char> isar_instance_get_path(
  ffi.Pointer<CIsarInstance> isar,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<ffi.Pointer<CIsarCollection>>,
    ffi.Uint64,
  )
>()
external int isar_instance_get_collection(
  ffi.Pointer<CIsarInstance> isar,
  ffi.Pointer<ffi.Pointer<CIsarCollection>> collection,
  int collection_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<CIsarTxn>,
    ffi.Bool,
    ffi.Bool,
    ffi.Pointer<ffi.Int64>,
  )
>()
external int isar_instance_get_size(
  ffi.Pointer<CIsarInstance> instance,
  ffi.Pointer<CIsarTxn> txn,
  bool include_indexes,
  bool include_links,
  ffi.Pointer<ffi.Int64> size,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
  )
>()
external void isar_instance_copy_to_file(
  ffi.Pointer<CIsarInstance> instance,
  ffi.Pointer<ffi.Char> path,
  int port,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<CIsarInstance>, ffi.Pointer<CIsarTxn>)
>()
external int isar_instance_verify(
  ffi.Pointer<CIsarInstance> instance,
  ffi.Pointer<CIsarTxn> txn,
);

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int isar_get_offsets(
  ffi.Pointer<CIsarCollection> collection,
  int embedded_col_id,
  ffi.Pointer<ffi.Uint32> offsets,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Int64,
    ffi.Int64,
  )
>()
external int isar_link(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int link_id,
  int id,
  int target_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Int64,
    ffi.Int64,
  )
>()
external int isar_link_unlink(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int link_id,
  int id,
  int target_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Int64,
  )
>()
external int isar_link_unlink_all(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int link_id,
  int id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Int64,
    ffi.Pointer<ffi.Int64>,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Bool,
  )
>()
external int isar_link_update_all(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int link_id,
  int id,
  ffi.Pointer<ffi.Int64> ids,
  int link_count,
  int unlink_count,
  bool replace,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint64,
    ffi.Pointer<ffi.Int64>,
    ffi.Uint32,
  )
>()
external int isar_link_verify(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int link_id,
  ffi.Pointer<ffi.Int64> ids,
  int ids_count,
);

@ffi.Native<ffi.Pointer<CQueryBuilder> Function(ffi.Pointer<CIsarCollection>)>()
external ffi.Pointer<CQueryBuilder> isar_qb_create(
  ffi.Pointer<CIsarCollection> collection,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<CQueryBuilder>, ffi.Int64, ffi.Int64)
>()
external int isar_qb_add_id_where_clause(
  ffi.Pointer<CQueryBuilder> builder,
  int start_id,
  int end_id,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CQueryBuilder>,
    ffi.Uint64,
    ffi.Pointer<CIndexKey>,
    ffi.Pointer<CIndexKey>,
    ffi.Bool,
    ffi.Bool,
  )
>()
external int isar_qb_add_index_where_clause(
  ffi.Pointer<CQueryBuilder> builder,
  int index_id,
  ffi.Pointer<CIndexKey> lower_key,
  ffi.Pointer<CIndexKey> upper_key,
  bool sort_asc,
  bool skip_duplicates,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CQueryBuilder>,
    ffi.Pointer<CIsarCollection>,
    ffi.Uint64,
    ffi.Int64,
  )
>()
external int isar_qb_add_link_where_clause(
  ffi.Pointer<CQueryBuilder> builder,
  ffi.Pointer<CIsarCollection> source_collection,
  int link_id,
  int id,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CQueryBuilder>, ffi.Pointer<CFilter>)
>()
external void isar_qb_set_filter(
  ffi.Pointer<CQueryBuilder> builder,
  ffi.Pointer<CFilter> filter,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<CQueryBuilder>, ffi.Uint64, ffi.Bool)
>()
external int isar_qb_add_sort_by(
  ffi.Pointer<CQueryBuilder> builder,
  int property_id,
  bool asc,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<CQueryBuilder>, ffi.Uint64, ffi.Bool)
>()
external int isar_qb_add_distinct_by(
  ffi.Pointer<CQueryBuilder> builder,
  int property_id,
  bool case_sensitive,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<CQueryBuilder>, ffi.Int64, ffi.Int64)
>()
external void isar_qb_set_offset_limit(
  ffi.Pointer<CQueryBuilder> builder,
  int offset,
  int limit,
);

@ffi.Native<ffi.Pointer<CQuery> Function(ffi.Pointer<CQueryBuilder>)>()
external ffi.Pointer<CQuery> isar_qb_build(ffi.Pointer<CQueryBuilder> builder);

@ffi.Native<ffi.Void Function(ffi.Pointer<CQuery>)>()
external void isar_q_free(ffi.Pointer<CQuery> query);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CQuery>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<CObjectSet>,
    ffi.Uint32,
  )
>()
external int isar_q_find(
  ffi.Pointer<CQuery> query,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<CObjectSet> result,
  int limit,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CQuery>,
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int isar_q_delete(
  ffi.Pointer<CQuery> query,
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  int limit,
  ffi.Pointer<ffi.Uint32> count,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CQuery>,
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CIsarTxn>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Uint32>,
  )
>()
external int isar_q_export_json(
  ffi.Pointer<CQuery> query,
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CIsarTxn> txn,
  ffi.Pointer<ffi.Char> id_name,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> json_bytes,
  ffi.Pointer<ffi.Uint32> json_length,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32)>()
external void isar_free_json(
  ffi.Pointer<ffi.Uint8> json_bytes,
  int json_length,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CQuery>,
    ffi.Pointer<CIsarTxn>,
    ffi.Uint8,
    ffi.Uint64,
    ffi.Pointer<ffi.Pointer<CAggregationResult>>,
  )
>()
external int isar_q_aggregate(
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CQuery> query,
  ffi.Pointer<CIsarTxn> txn,
  int operation,
  int property_id,
  ffi.Pointer<ffi.Pointer<CAggregationResult>> result,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<CAggregationResult>)>()
external int isar_q_aggregate_long_result(
  ffi.Pointer<CAggregationResult> result,
);

@ffi.Native<ffi.Double Function(ffi.Pointer<CAggregationResult>)>()
external double isar_q_aggregate_double_result(
  ffi.Pointer<CAggregationResult> result,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<ffi.Pointer<CIsarTxn>>,
    ffi.Bool,
    ffi.Bool,
    ffi.Bool,
    ffi.Int64,
  )
>()
external int isar_txn_begin(
  ffi.Pointer<CIsarInstance> isar,
  ffi.Pointer<ffi.Pointer<CIsarTxn>> txn,
  bool sync,
  bool write,
  bool silent,
  int port,
);

@ffi.Native<ffi.Int64 Function(ffi.Pointer<CIsarTxn>, ffi.Bool)>()
external int isar_txn_finish(ffi.Pointer<CIsarTxn> txn, bool commit);

@ffi.Native<
  ffi.Pointer<CWatchHandle> Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<CIsarCollection>,
    ffi.Int64,
  )
>()
external ffi.Pointer<CWatchHandle> isar_watch_collection(
  ffi.Pointer<CIsarInstance> isar,
  ffi.Pointer<CIsarCollection> collection,
  int port,
);

@ffi.Native<
  ffi.Pointer<CWatchHandle> Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<CIsarCollection>,
    ffi.Int64,
    ffi.Int64,
  )
>()
external ffi.Pointer<CWatchHandle> isar_watch_object(
  ffi.Pointer<CIsarInstance> isar,
  ffi.Pointer<CIsarCollection> collection,
  int id,
  int port,
);

@ffi.Native<
  ffi.Pointer<CWatchHandle> Function(
    ffi.Pointer<CIsarInstance>,
    ffi.Pointer<CIsarCollection>,
    ffi.Pointer<CQuery>,
    ffi.Int64,
  )
>()
external ffi.Pointer<CWatchHandle> isar_watch_query(
  ffi.Pointer<CIsarInstance> isar,
  ffi.Pointer<CIsarCollection> collection,
  ffi.Pointer<CQuery> query,
  int port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<CWatchHandle>)>()
external void isar_stop_watching(ffi.Pointer<CWatchHandle> handle);

final class CAggregationResult extends ffi.Opaque {}

final class CIsarTxn extends ffi.Opaque {}

final class CFilter extends ffi.Opaque {}

final class CIndexKey extends ffi.Opaque {}

final class CIsarCollection extends ffi.Opaque {}

final class CIsarInstance extends ffi.Opaque {}

final class CQuery extends ffi.Opaque {}

final class CQueryBuilder extends ffi.Opaque {}

final class CWatchHandle extends ffi.Opaque {}

final class CObject extends ffi.Struct {
  @ffi.Int64()
  external int id;

  external ffi.Pointer<ffi.Uint8> buffer;

  @ffi.Uint32()
  external int buffer_length;
}

final class CObjectSet extends ffi.Struct {
  external ffi.Pointer<CObject> objects;

  @ffi.Uint32()
  external int length;
}

final class CDartCObject extends ffi.Opaque {}

const int IsarIndex_MAX_STRING_INDEX_SIZE = 1024;

const int IsarObject_NULL_BYTE = 0;

const int IsarObject_NULL_BOOL = 0;

const int IsarObject_FALSE_BOOL = 1;

const int IsarObject_TRUE_BOOL = 2;

const int IsarObject_NULL_INT = -2147483648;

const int IsarObject_NULL_LONG = -9223372036854775808;

const int IsarObject_MAX_SIZE = 33554432;

const int SchemaManager_ISAR_FILE_VERSION = 2;
