// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//
//    dart --enable-experiment=native-assets tool/generate_asset_hashes.dart
//

/// A map from asset file names to their SHA256 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
  'isar_aarch64-pc-windows-msvc.dll':
      'f9517515bc4a41e950d14ca2a47c1dcd24464a45caf7adf08f7e4607a1c0acdf',
  'isar_x86_64-pc-windows-msvc.dll':
      '488713a5ecfd92fec715cd13e05cef6b6a16a72ed9d46d62da9368a7aa11bdae',
  'libisar_aarch64-apple-darwin.dylib':
      '7060ef457c08f42aa569242b702876200e6f0c0235406f671e9f45f5e9655ce5',
  'libisar_aarch64-apple-ios-sim.dylib':
      '121fae9e24be6fdfee0f9d1d67383485b0d5be6c206234927a15ec350fa977e4',
  'libisar_aarch64-apple-ios.dylib':
      'f7fa6744dd0a2fa828a2cfe3b2a037c371a28bfd07a88548f52f1bfdeaa1d373',
  'libisar_aarch64-linux-android.so':
      '880bf2b5c172033dab6d7552aa9da0c90cfcbd7f46cf0083d89061d324bdbbe8',
  'libisar_aarch64-unknown-linux-gnu.so':
      '69e03902ce56b7d3b8d217ec521439929205bfbbfac72e87fb1d247f123d8d9e',
  'libisar_armv7-linux-androideabi.so':
      '62b09085bf6f26773c5c7087b0cb1694b4a205ca67aa6d9b64047eddb36b66de',
  'libisar_x86_64-apple-darwin.dylib':
      '490f8a5f76366c4cdc87a8106ea4b09d5c0920c1a0a4734bf1dbf645b6863531',
  'libisar_x86_64-apple-ios.dylib':
      'dd82347e1de0e14bb5de33ed6adaeaa842fe2376d664c563abff1dac92616d49',
  'libisar_x86_64-linux-android.so':
      '68ae2094cf27f1e68e18c896bd6bfc9cc25651c10c32a162a9e11b6f7dd5a046',
  'libisar_x86_64-unknown-linux-gnu.so':
      'e8e5a907df2544f5fa5d9657c23747d7b243c152f149ecccd30e374486e52786',
};
