// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//
//    dart --enable-experiment=native-assets tool/generate_asset_hashes.dart
//

/// A map from asset file names to their SHA256 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
  'isar_aarch64-pc-windows-msvc.dll':
      'b9aac94fef1c8a289efef9961f0899edc3f8e5e8624737f0bea0444f984e2391',
  'isar_x86_64-pc-windows-msvc.dll':
      '5ee43b9b309ac18b50487a559f8db074e6f28af4cc3a633c36f74b4e62671adf',
  'libisar_aarch64-apple-darwin.dylib':
      'ab4e10be44e1ff558223a41f319cb6f1d3d72a51fdf4dfcfc80453a442b3dbe0',
  'libisar_aarch64-apple-ios-sim.dylib':
      'e7fc9e61ebccde0ea992fcfbc385264a94ac7d608a8fb2a28fee6bb208f7c80b',
  'libisar_aarch64-apple-ios.dylib':
      '2541a8616cbcdf5912f1c460bda1163e97ca4617f7160f243273932bd510a67d',
  'libisar_aarch64-linux-android.so':
      '57411a7535386f456d02836ef1f20d2273086500d85fa7772ceb0a4452e7dc64',
  'libisar_aarch64-unknown-linux-gnu.so':
      'ded92a103a42e0690079a0d0324e506c688da4a2609a2a2e96308b10c31cf6be',
  'libisar_armv7-linux-androideabi.so':
      '27c66c541aa519479fe7dc93cd780f4bcecb53f42235bc546d762e5882871805',
  'libisar_x86_64-apple-darwin.dylib':
      '4719058ed229a1379f9ea12b2d2c91155d204daa02eb7550c294a33f449fc36c',
  'libisar_x86_64-apple-ios.dylib':
      '4e462ed6e6a92a4b0245c97c4b31a50df1e1462e2def1d95f4a29476929224fc',
  'libisar_x86_64-linux-android.so':
      'f48b1f0140faf743804e4aea93d774a6014ab1eb6f53f61cc0b593a8df37956a',
  'libisar_x86_64-unknown-linux-gnu.so':
      'dbf12a554c5867dcabd7351beea04b1a93ac575c923519ed46526269cae2cc33',
};
