// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//
//    dart --enable-experiment=native-assets tool/generate_asset_hashes.dart
//

/// A map from asset file names to their SHA256 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
  'isar_aarch64-pc-windows-msvc.dll':
      'f73d8c055b8a9d79b0209285686c02c01d13255dc42fb6bec9f521dcc545264a',
  'isar_x86_64-pc-windows-msvc.dll':
      '584502ea24738825876bb112d312e100e052d1ce5b43b0dadd8980923514cb46',
  'libisar_aarch64-apple-darwin.dylib':
      '9425b5bb5616bd6438035fbb66f0657fc4f19bf559416cad5bcce4b12ca637e1',
  'libisar_aarch64-apple-ios-sim.dylib':
      '0910d2c6611a938f3403c52f4733596728a031bb31f7377ffb7fa2ce2db897be',
  'libisar_aarch64-apple-ios.dylib':
      '174c15197794dc1659a256ef401d351c5cd035fedf98fd1731d7b7a3a69ffd21',
  'libisar_aarch64-linux-android.so':
      'c320e27cc5da27fdaa498bd3981cc0cd504656da012203f10b933d148a4d7033',
  'libisar_aarch64-unknown-linux-gnu.so':
      '5f2137699c395088470637278ca3a538874814bb75dce68355d8d5a2b2cedaba',
  'libisar_armv7-linux-androideabi.so':
      '4b24b81677ca1c82c45257b789bb3a64f418010db299d77716d9554b7d929284',
  'libisar_x86_64-apple-darwin.dylib':
      '1759882e66387de0abb113c243a50b7f09e93a141dd7ea472848b57c03bb2410',
  'libisar_x86_64-apple-ios.dylib':
      '2dd37f7210924dfe900005e9d4795acf88bbb071c2915c3b072846aac12e5f4b',
  'libisar_x86_64-linux-android.so':
      '8c65902e3571502ea874a1243ba4dd37aaafe5ee6817cd4428aeba5d65eec4af',
  'libisar_x86_64-unknown-linux-gnu.so':
      'a4bb20993822220ae3708844c2c7cbf4e8556efcbb4a4369cd0aea6e70df7956',
};
