import 'dart:io';

import 'package:dart_style/dart_style.dart';
import 'package:isar_community/src/hook_helpers/download.dart';
import 'package:isar_community/src/hook_helpers/hashes.dart';

/// Regenerates [assetHashes].
Future<void> main(List<String> args) async {
  final assetsDir = Directory.fromUri(
    Platform.script.resolve('../.dart_tool/isar_community/'),
  );
  if (assetsDir.existsSync()) {
    await assetsDir.delete(recursive: true);
  }
  await assetsDir.create(recursive: true);
  final hashes = Map.fromEntries(
    await Future.wait([
      for (final name in assetHashes.keys)
        downloadAsset(
          name,
          assetsDir,
        ).then((file) => MapEntry(name, hashAsset(file))),
    ]),
  );

  await writeHashesFile(hashes);
}

Future<void> writeHashesFile(Map<String, String> assetHashes) async {
  final hashesFile = File.fromUri(
    Platform.script.resolve('../lib/src/hook_helpers/hashes.dart'),
  );
  await hashesFile.create(recursive: true);
  final source = [
    '''
// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//
//    dart --enable-experiment=native-assets tool/generate_asset_hashes.dart
//

/// A map from asset file names to their SHA256 hashes.
///
/// Used to verify the integrity of downloaded assets.
const assetHashes = <String, String>{
''',
    for (final hash in assetHashes.entries) "  '${hash.key}': '${hash.value}',",
    '};',
  ].join('\n');
  await hashesFile.writeAsString(
    DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format(source),
  );
}
